[[repositories]]
path = "."
prefix = ""
repos = [
  "git@github.com:mirrorboards/.vscode.git",
]

# mirrorboards
[[repositories]]
path = "mirrorboards"
prefix = ""
repos = [
  "git@github.com:mirrorboards/mirrorboards.git",
  "git@github.com:mirrorboards/mirrorboards-ts.git",
  "git@github.com:mirrorboards/mirrorboards-go.git",
]
[[repositories]]
path = "mirrorboards"
prefix = "mirrorboards"
repos = [
  "git@github.com:mirrorboards/platform.git",
]

# mirrorboards-utils
[[repositories]]
path = "mirrorboards-utils"
prefix = "mirrorboards"
repos = [
  "git@github.com:mirrorboards/init.git",
  "git@github.com:mirrorboards/fish.git",
]

# .legacy
[[repositories]]
path = ".legacy"
prefix = ""
repos = [
  "git@github.com:mirrorboards/mirrorboards-next-next.git",
  "git@github.com:mirrorboards/mirrorboards-dev.git",
  "git@github.com:mirrorboards/mirrorboards-next.git",
  "git@github.com:mirrorboards/mirrorboards-dev2.git",
  "git@github.com:mirrorboards/mirrorboards-legacy.git",
]

# mirrorboards-exchange
[[repositories]]
path = "mirrorboards-exchange"
prefix = "mirrorboards-exchange"
repos = [
  "git@github.com:Mirrorboards-Exchange/operations.git",
  "git@github.com:Mirrorboards-Exchange/platform.git",
]

# pay2vault
[[repositories]]
path = "pay2vault"
prefix = ""
repos = [
  "git@github.com:mirrorboards/pay2vault.git",
  "git@github.com:mirrorboards/pay2vault-platform.git",
]
